Repository interview-partner/interview-partner, pull requests merged in 2024-05, with the labels that each got.

#2 chore: Backend Project 초기 설정
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/vip/interviewpartner/InterviewPartnerApplication.java
  server/src/test/java/com/vip/interviewpartner/InterviewPartnerApplicationTests.java
Labels: 🔥 BE, ⚙ Setting

#4 chore: front-end 기본 프로젝트 설정
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
Labels: 🌈 FE, ⚙ Setting

#8 feat: 회원가입 기능 구현
  server/build.gradle
  server/src/main/java/com/vip/interviewpartner/common/ApiCommonResponse.java
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/common/exception/GlobalExceptionHandler.java
  server/src/main/java/com/vip/interviewpartner/config/.gitkeep
  server/src/main/java/com/vip/interviewpartner/config/EncoderConfig.java
  server/src/main/java/com/vip/interviewpartner/config/SecurityConfig.java
  server/src/main/java/com/vip/interviewpartner/config/SpringDocConfig.java
  server/src/main/java/com/vip/interviewpartner/controller/.gitkeep
  server/src/main/java/com/vip/interviewpartner/controller/MemberController.java
  server/src/main/java/com/vip/interviewpartner/domain/Member.java
  server/src/main/java/com/vip/interviewpartner/dto/.gitkeep
  server/src/main/java/com/vip/interviewpartner/dto/MemberJoinRequest.java
  server/src/main/java/com/vip/interviewpartner/repository/MemberRepository.java
  server/src/main/java/com/vip/interviewpartner/service/.gitkeep
  server/src/main/java/com/vip/interviewpartner/service/MemberJoinService.java
  server/src/test/java/com/vip/interviewpartner/service/MemberJoinServiceTest.java
Labels: 🔥 BE, ✨ Feature

#13 feat: 닉네임 중복 체크 API 추가
  server/src/main/java/com/vip/interviewpartner/common/ApiCommonResponse.java
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/common/exception/GlobalExceptionHandler.java
  server/src/main/java/com/vip/interviewpartner/config/SecurityConfig.java
  server/src/main/java/com/vip/interviewpartner/controller/MemberController.java
  server/src/main/java/com/vip/interviewpartner/dto/NicknameCheckResponse.java
  server/src/main/java/com/vip/interviewpartner/service/MemberJoinService.java
Labels: 🔥 BE, ✨ Feature

#16 feat: 회원가입 페이지 개발
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/accountBox/accountContext.js
  client/src/components/accountBox/common.jsx
  client/src/components/accountBox/index.jsx
  client/src/components/accountBox/loginForm.jsx
  client/src/components/accountBox/signupForm.jsx
  client/src/components/marginer/index.jsx
  client/src/config.js
  client/src/index.css
  client/src/styles/colors.jsx
  client/src/utils/validators.jsx
Labels: 🌈 FE, ✨ Feature

#17 feat: 자체 로그인 기능 구현
  docker-compose.dev.yml
  server/build.gradle
  server/src/main/java/com/vip/interviewpartner/common/constants/Constants.java
  server/src/main/java/com/vip/interviewpartner/common/exception/CustomAccessDeniedHandler.java
  server/src/main/java/com/vip/interviewpartner/common/exception/CustomAuthenticationEntryPoint.java
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/common/exception/ExceptionHandlingFilter.java
  server/src/main/java/com/vip/interviewpartner/common/jwt/JWTFilter.java
  server/src/main/java/com/vip/interviewpartner/common/jwt/JWTUtil.java
  server/src/main/java/com/vip/interviewpartner/common/jwt/LoginFilter.java
  server/src/main/java/com/vip/interviewpartner/config/RedisConfig.java
  server/src/main/java/com/vip/interviewpartner/config/SecurityConfig.java
  server/src/main/java/com/vip/interviewpartner/config/SpringDocConfig.java
  server/src/main/java/com/vip/interviewpartner/controller/AuthController.java
  server/src/main/java/com/vip/interviewpartner/domain/Member.java
  server/src/main/java/com/vip/interviewpartner/dto/CustomUserDetails.java
  server/src/main/java/com/vip/interviewpartner/dto/LoginRequest.java
  server/src/main/java/com/vip/interviewpartner/dto/RefreshTokenData.java
  server/src/main/java/com/vip/interviewpartner/repository/MemberRepository.java
  server/src/main/java/com/vip/interviewpartner/repository/RefreshTokenRepository.java
  server/src/main/java/com/vip/interviewpartner/service/CustomUserDetailsService.java
  server/src/main/java/com/vip/interviewpartner/service/TokenService.java
Labels: 🔥 BE, ✨ Feature

#20 feat: JWT 토큰 재발행 API 작성
  server/src/main/java/com/vip/interviewpartner/common/constants/Constants.java
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/common/jwt/JWTFilter.java
  server/src/main/java/com/vip/interviewpartner/common/jwt/JWTUtil.java
  server/src/main/java/com/vip/interviewpartner/common/jwt/LoginFilter.java
  server/src/main/java/com/vip/interviewpartner/config/SecurityConfig.java
  server/src/main/java/com/vip/interviewpartner/config/SpringDocConfig.java
  server/src/main/java/com/vip/interviewpartner/controller/AuthController.java
  server/src/main/java/com/vip/interviewpartner/controller/MemberController.java
  server/src/main/java/com/vip/interviewpartner/dto/CustomUserDetails.java
  server/src/main/java/com/vip/interviewpartner/dto/MemberJoinRequest.java
  server/src/main/java/com/vip/interviewpartner/repository/RefreshTokenRepository.java
  server/src/main/java/com/vip/interviewpartner/service/TokenService.java
Labels: 🔥 BE, ✨ Feature

#22 feat: 이력서 텍스트 추출 기능 구현
  server/build.gradle
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/controller/MemberController.java
  server/src/main/java/com/vip/interviewpartner/service/ExportTextService.java
  server/src/main/java/com/vip/interviewpartner/service/ResumeUploadService.java
Labels: 🔥 BE, ✨ Feature

#23 feat: 로그아웃 API 작성
  server/src/main/java/com/vip/interviewpartner/common/jwt/JWTFilter.java
  server/src/main/java/com/vip/interviewpartner/common/jwt/JWTUtil.java
  server/src/main/java/com/vip/interviewpartner/common/jwt/LoginFilter.java
  server/src/main/java/com/vip/interviewpartner/controller/AuthController.java
  server/src/main/java/com/vip/interviewpartner/service/TokenService.java
Labels: 🔥 BE, ✨ Feature

#24 Feat: 로그인 페이지 개발
  client/src/components/accountBox/index.jsx
  client/src/components/accountBox/loginForm.jsx
  client/src/components/accountBox/signupForm.jsx
  client/src/components/common/common.jsx
  client/src/components/common/marginer/marginer.jsx
  client/src/fonts/Pretendard-ExtraBold.otf
  client/src/fonts/Pretendard-ExtraLight.otf
  client/src/fonts/Pretendard-Light.otf
  client/src/fonts/Pretendard-Medium.otf
  client/src/fonts/Pretendard-Regular.otf
  client/src/fonts/Pretendard-SemiBold.otf
  client/src/fonts/Pretendard-Thin.otf
  client/src/fonts/font.css
  client/src/images/google_logo_round.png
  client/src/images/kakao_logo_round.png
  client/src/images/naver_logo_round.png
  client/src/index.css
  client/src/index.js
  client/src/services/loginService.js
  client/src/services/signupService.js
  client/src/styles/colors.jsx
  client/src/utils/validators.jsx
Labels: 🌈 FE, 🔨 Refactor, ✨ Feature

#26 feat: 추출된 텍스트 txt로 저장 기능 구현
  server/src/main/java/com/vip/interviewpartner/service/ExportTextService.java
  server/src/main/java/com/vip/interviewpartner/service/ResumeUploadService.java
  server/src/main/java/com/vip/interviewpartner/service/StringToTxtService.java
Labels: 🔨 Refactor, 🔥 BE, ✨ Feature

#33 feat: Native 소셜 로그인 구현
  server/build.gradle
  server/src/main/java/com/vip/interviewpartner/common/constants/Constants.java
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/common/oauth2/CustomSuccessHandler.java
  server/src/main/java/com/vip/interviewpartner/config/SecurityConfig.java
  server/src/main/java/com/vip/interviewpartner/config/SpringDocConfig.java
  server/src/main/java/com/vip/interviewpartner/domain/Member.java
  server/src/main/java/com/vip/interviewpartner/dto/CustomUserDetails.java
  server/src/main/java/com/vip/interviewpartner/dto/KakaoResponse.java
  server/src/main/java/com/vip/interviewpartner/dto/MemberJoinRequest.java
  server/src/main/java/com/vip/interviewpartner/dto/NaverResponse.java
  server/src/main/java/com/vip/interviewpartner/dto/OAuth2Response.java
  server/src/main/java/com/vip/interviewpartner/repository/MemberRepository.java
  server/src/main/java/com/vip/interviewpartner/service/CustomOAuth2UserService.java
  server/src/main/java/com/vip/interviewpartner/service/CustomUserDetailsService.java
  server/src/test/java/com/vip/interviewpartner/InterviewPartnerApplicationTests.java
  server/src/test/java/com/vip/interviewpartner/service/CustomOAuth2UserServiceTest.java
  server/src/test/java/com/vip/interviewpartner/service/MemberJoinServiceTest.java
Labels: 🔥 BE, ✨ Feature

#35 feat: 페이지 라우팅 구현
  client/src/App.js
  client/src/assets/fonts/Pretendard-ExtraBold.otf
  client/src/assets/fonts/Pretendard-ExtraLight.otf
  client/src/assets/fonts/Pretendard-Light.otf
  client/src/assets/fonts/Pretendard-Medium.otf
  client/src/assets/fonts/Pretendard-Regular.otf
  client/src/assets/fonts/Pretendard-SemiBold.otf
  client/src/assets/fonts/Pretendard-Thin.otf
  client/src/assets/fonts/font.css
  client/src/assets/images/google_logo_round.png
  client/src/assets/images/kakao_logo_round.png
  client/src/assets/images/letterLogo.png
  client/src/assets/images/mainpageImage.jpg
  client/src/assets/images/naver_logo_round.png
  client/src/assets/images/roundlogoWhite.png
  client/src/assets/images/원형로고 색.png
  client/src/components/layout/navBar.js
  client/src/features/login/accountBox/accountContext.js
  client/src/features/login/accountBox/index.jsx
  client/src/features/login/accountBox/loginForm.jsx
  client/src/features/login/accountBox/signupForm.jsx
  client/src/fonts/Pretendard-Black.woff
  client/src/fonts/Pretendard-Bold.woff
  client/src/fonts/Pretendard-ExtraBold.woff
  client/src/fonts/Pretendard-ExtraLight.woff
  client/src/fonts/Pretendard-Light.woff
  client/src/fonts/Pretendard-Medium.woff
  client/src/fonts/Pretendard-Regular.woff
  client/src/fonts/Pretendard-SemiBold.woff
  client/src/fonts/Pretendard-Thin.woff
  client/src/index.css
  client/src/index.js
  client/src/pages/aiinterview/aiinterview.css
  client/src/pages/aiinterview/aiinterview.jsx
  client/src/pages/interviewroom/interviewroom.css
  client/src/pages/interviewroom/interviewroom.jsx
  client/src/pages/login/login.css
  client/src/pages/login/login.jsx
  client/src/pages/main/main.css
  client/src/pages/main/main.jsx
  client/src/pages/mockupcommunity/mockupcommunity.css
  client/src/pages/mockupcommunity/mockupcommunity.jsx
  client/src/pages/mockuproom/mockuproom.css
  client/src/pages/mockuproom/mockuproom.jsx
  client/src/pages/mypage/mypage.css
  client/src/pages/mypage/mypage.jsx
  client/src/pages/signup/signup.css
  client/src/pages/signup/signup.jsx
Labels: 🌈 FE, ✨ Feature

#38 feat: Firebase 구글 로그인 구현
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/vip/interviewpartner/common/constants/Constants.java
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/common/jwt/LoginFilter.java
  server/src/main/java/com/vip/interviewpartner/common/oauth2/FirebaseTokenFilter.java
  server/src/main/java/com/vip/interviewpartner/common/util/ResponseFilterUtil.java
  server/src/main/java/com/vip/interviewpartner/config/FirebaseConfig.java
  server/src/main/java/com/vip/interviewpartner/config/SecurityConfig.java
  server/src/main/java/com/vip/interviewpartner/config/SpringDocConfig.java
  server/src/main/java/com/vip/interviewpartner/dto/GoogleResponse.java
  server/src/main/java/com/vip/interviewpartner/service/CustomOAuth2UserService.java
Labels: 🔥 BE, ✨ Feature

#42 feat: 모의면접 방 태그 생성 API 작성
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/controller/TagController.java
  server/src/main/java/com/vip/interviewpartner/domain/Tag.java
  server/src/main/java/com/vip/interviewpartner/dto/TagCreateRequest.java
  server/src/main/java/com/vip/interviewpartner/dto/TagResponse.java
  server/src/main/java/com/vip/interviewpartner/repository/TagRepository.java
  server/src/main/java/com/vip/interviewpartner/service/TagService.java
  server/src/test/java/com/vip/interviewpartner/service/TagServiceTest.java
Labels: 🔥 BE, ✨ Feature

#45 feat: 모의면접 방 태그 검색 API 작성
  db/init.sql
  server/src/main/java/com/vip/interviewpartner/controller/TagController.java
  server/src/main/java/com/vip/interviewpartner/domain/Tag.java
  server/src/main/java/com/vip/interviewpartner/repository/TagRepository.java
  server/src/main/java/com/vip/interviewpartner/service/TagService.java
Labels: 🔥 BE, ✨ Feature

#49 feat: 소셜 로그인 API 적용
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/config.js
  client/src/features/login/accountBox/loginForm.jsx
  client/src/pages/tokenreissue/tokenreissue.jsx
  client/src/services/axiosConfig.js
  client/src/services/googleLoginService.js
  client/src/services/loginService.js
  client/src/services/signupService.js
Labels: 🌈 FE, ⚙ Setting, ✨ Feature

#51 feat: 모의면접 방 생성 API 작성
  LICENSE
  NOTICE
  server/build.gradle
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/controller/RoomController.java
  server/src/main/java/com/vip/interviewpartner/domain/Room.java
  server/src/main/java/com/vip/interviewpartner/domain/RoomTag.java
  server/src/main/java/com/vip/interviewpartner/domain/Tag.java
  server/src/main/java/com/vip/interviewpartner/dto/RoomCreateRequest.java
  server/src/main/java/com/vip/interviewpartner/dto/RoomCreateResponse.java
  server/src/main/java/com/vip/interviewpartner/service/OpenViduService.java
  server/src/main/java/com/vip/interviewpartner/service/RoomCreateService.java
Labels: 🔥 BE, ✨ Feature

#56 feat: 모의면접 방 태그 검색 및 추가 API 적용
  client/src/pages/mockupcommunity/MockupCommunityStyles.jsx
  client/src/pages/mockupcommunity/ModalComponent.jsx
  client/src/pages/mockupcommunity/ModalStyles.jsx
  client/src/pages/mockupcommunity/mockupcommunity.jsx
  client/src/services/tagService.js
  client/src/utils/tagUtils.jsx
  client/src/utils/validators.jsx
Labels: 🌈 FE, ✨ Feature

#54 feat: 모의면접 방 목록 조회 API 작성
  db/init.sql
  docker-compose.dev.yml
  server/src/main/java/com/vip/interviewpartner/config/SecurityConfig.java
  server/src/main/java/com/vip/interviewpartner/controller/RoomController.java
  server/src/main/java/com/vip/interviewpartner/domain/RoomStatus.java
  server/src/main/java/com/vip/interviewpartner/dto/RoomResponseDTO.java
  server/src/main/java/com/vip/interviewpartner/repository/RoomRepository.java
  server/src/main/java/com/vip/interviewpartner/service/OpenViduService.java
  server/src/main/java/com/vip/interviewpartner/service/RoomLookupService.java
Labels: 🔥 BE, ✨ Feature

#57 feat: AI 프롬프트 페이지 구현
  client/public/index.html
  client/src/App.js
  client/src/components/button/arrowButton.jsx
  client/src/components/button/showPaper.jsx
  client/src/components/textbox/aidialogBox.jsx
  client/src/features/banner/interviewInfo.jsx
  client/src/features/chat/interviewChat.jsx
  client/src/pages/interviewroom/interviewroom.jsx
  client/src/pages/promptroom/promptroom.css
  client/src/pages/promptroom/promptroom.jsx
  client/src/pages/voiceroom/voiceroom.css
  client/src/pages/voiceroom/voiceroom.jsx
  client/src/styles/colors.jsx
Labels: 🌈 FE, ✨ Feature

#60 feat: 모의면접 방 입장 API 작성
  docker-compose.dev.yml
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/controller/RoomController.java
  server/src/main/java/com/vip/interviewpartner/domain/Room.java
  server/src/main/java/com/vip/interviewpartner/domain/RoomParticipant.java
  server/src/main/java/com/vip/interviewpartner/dto/RoomEnterRequest.java
  server/src/main/java/com/vip/interviewpartner/dto/RoomEnterResponse.java
  server/src/main/java/com/vip/interviewpartner/dto/RoomEnterUserData.java
  server/src/main/java/com/vip/interviewpartner/service/MemberService.java
  server/src/main/java/com/vip/interviewpartner/service/OpenViduService.java
  server/src/main/java/com/vip/interviewpartner/service/ResumeService.java
  server/src/main/java/com/vip/interviewpartner/service/RoomEnterService.java
  server/src/main/java/com/vip/interviewpartner/service/RoomService.java
  server/src/test/java/com/vip/interviewpartner/InterviewPartnerApplicationTests.java
Labels: 🔥 BE, ✨ Feature

#63 feat: 모의면접 방 생성 API 적용
  client/src/assets/icons/close_Icon.png
  client/src/features/login/accountBox/loginForm.jsx
  client/src/pages/mockupcommunity/ModalComponent.jsx
  client/src/pages/mockupcommunity/ModalStyles.jsx
  client/src/pages/mockupcommunity/mockupcommunity.jsx
  client/src/services/roomService.js
  client/src/utils/tagUtils.jsx
  client/src/utils/validators.jsx
Labels: 🌈 FE, ✨ Feature

#65 feat: 이력서 조회 API 작성
  server/src/main/java/com/vip/interviewpartner/controller/MemberController.java
  server/src/main/java/com/vip/interviewpartner/dto/ResumeLookupResponse.java
  server/src/main/java/com/vip/interviewpartner/repository/ResumeRepository.java
  server/src/main/java/com/vip/interviewpartner/service/ResumeService.java
Labels: 🔥 BE, ✨ Feature

#69 refactor: 방 목록 조회 시 페이징 정보 추가
  server/src/main/java/com/vip/interviewpartner/controller/RoomController.java
  server/src/main/java/com/vip/interviewpartner/dto/PageCustom.java
  server/src/main/java/com/vip/interviewpartner/dto/PageableCustom.java
  server/src/main/java/com/vip/interviewpartner/service/RoomLookupService.java
Labels: 🔥 BE, ✨ Feature

#70 Feature/#67 connect fetch room api
  client/src/pages/mockupcommunity/mockupcommunity.jsx
  client/src/services/roomService.js
  client/src/testdata/testroom.js
Labels: 🌈 FE, ✨ Feature

#66 feat: AI 면접 생성
  client/src/pages/mockupcommunity/mockupcommunity.jsx
  client/src/services/roomService.js
  db/init.sql
  server/build.gradle
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/controller/InterviewController.java
  server/src/main/java/com/vip/interviewpartner/domain/Interview.java
  server/src/main/java/com/vip/interviewpartner/domain/Question.java
  server/src/main/java/com/vip/interviewpartner/dto/AiInterviewRequest.java
  server/src/main/java/com/vip/interviewpartner/service/AiInterviewCreateService.java
  server/src/main/java/com/vip/interviewpartner/service/QuestionMakingService.java
  server/src/main/java/com/vip/interviewpartner/service/S3DownloadService.java
Labels: 🔥 BE, ✨ Feature

#72 feat: 모의면접 방 웹훅 기능 추가
  db/init.sql
  docker-compose.dev.yml
  server/src/main/java/com/vip/interviewpartner/config/SecurityConfig.java
  server/src/main/java/com/vip/interviewpartner/controller/WebhookController.java
  server/src/main/java/com/vip/interviewpartner/domain/Room.java
  server/src/main/java/com/vip/interviewpartner/domain/RoomParticipant.java
  server/src/main/java/com/vip/interviewpartner/dto/RoomEnterUserData.java
  server/src/main/java/com/vip/interviewpartner/repository/RoomRepository.java
  server/src/main/java/com/vip/interviewpartner/service/RoomEnterService.java
  server/src/main/java/com/vip/interviewpartner/service/RoomParticipantService.java
  server/src/main/java/com/vip/interviewpartner/service/WebhookService.java
Labels: 🔥 BE, ✨ Feature

#71 feat: aiinterview 페이지 api 제외 프론트 구현
  client/src/assets/icons/circle.png
  client/src/assets/icons/counter_1.png
  client/src/assets/icons/counter_2.png
  client/src/assets/icons/counter_3.png
  client/src/components/button/RoundButton.jsx
  client/src/components/button/counterButton.jsx
  client/src/components/button/smallsquareButton.jsx
  client/src/components/shape/ActivePoint.jsx
  client/src/components/shape/UnActivePoint.jsx
  client/src/features/input/InputInterviewInfo.jsx
  client/src/features/input/InputInterviewSetting.jsx
  client/src/features/input/InputPersonalInfo.jsx
  client/src/features/input/Inputready.jsx
  client/src/features/show-progress/SelectInterviewInfo.jsx
  client/src/pages/aiinterview/aiinterview.css
  client/src/pages/aiinterview/aiinterview.jsx
Labels: 🌈 FE, ✨ Feature

#77 feat: 모의면접 방 채팅 저장 기능 구현
  docker-compose.dev.yml
  server/src/main/java/com/vip/interviewpartner/common/constants/Constants.java
  server/src/main/java/com/vip/interviewpartner/common/constants/WebhookEvent.java
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/common/util/DateTimeUtil.java
  server/src/main/java/com/vip/interviewpartner/domain/Message.java
  server/src/main/java/com/vip/interviewpartner/dto/RoomChatDTO.java
  server/src/main/java/com/vip/interviewpartner/service/OpenViduService.java
  server/src/main/java/com/vip/interviewpartner/service/WebhookService.java
Labels: 🔥 BE, ✨ Feature

#76 feat: 방 입장을 위한 이력서 조회 API 및 방 입장 API 적용
  client/src/pages/mockupcommunity/CreateRoomModalComponent.jsx
  client/src/pages/mockupcommunity/CreateRoomModalStyles.jsx
  client/src/pages/mockupcommunity/ResumeSelectModal.jsx
  client/src/pages/mockupcommunity/ResumeSelectModalStyles.jsx
  client/src/pages/mockupcommunity/mockupcommunity.jsx
  client/src/services/resumeService.js
  client/src/services/roomService.js
Labels: 🌈 FE, ✨ Feature

#82 feat: 자신의 회원정보 조회 API 추가
  server/src/main/java/com/vip/interviewpartner/controller/MemberController.java
  server/src/main/java/com/vip/interviewpartner/dto/MemberInfoResponse.java
  server/src/main/java/com/vip/interviewpartner/service/MemberService.java
  server/src/main/java/com/vip/interviewpartner/service/ResumeUploadService.java
Labels: 🔥 BE, ✨ Feature

#79 feat: 모의면접 피드백 API 작성
  db/init.sql
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/controller/FeedbackController.java
  server/src/main/java/com/vip/interviewpartner/controller/InterviewController.java
  server/src/main/java/com/vip/interviewpartner/domain/Feedback.java
  server/src/main/java/com/vip/interviewpartner/domain/Message.java
  server/src/main/java/com/vip/interviewpartner/domain/Room.java
  server/src/main/java/com/vip/interviewpartner/dto/FeedbackCreateRequest.java
  server/src/main/java/com/vip/interviewpartner/dto/RoomChatDTO.java
  server/src/main/java/com/vip/interviewpartner/repository/FeedbackRepository.java
  server/src/main/java/com/vip/interviewpartner/service/FeedbackCreateService.java
  server/src/main/java/com/vip/interviewpartner/service/RoomParticipantService.java
  server/src/main/java/com/vip/interviewpartner/service/WebhookService.java
Labels: 🔥 BE, ✨ Feature

#85 feat: 회원정보 수정 API 작성
  server/src/main/java/com/vip/interviewpartner/controller/MemberController.java
  server/src/main/java/com/vip/interviewpartner/domain/Member.java
  server/src/main/java/com/vip/interviewpartner/dto/MemberUpdateRequest.java
  server/src/main/java/com/vip/interviewpartner/service/MemberJoinService.java
  server/src/main/java/com/vip/interviewpartner/service/MemberService.java
  server/src/test/java/com/vip/interviewpartner/service/MemberJoinServiceTest.java
Labels: 🔥 BE, ✨ Feature

#86 feat: AI 면접 질문 조회 API 작성
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/controller/InterviewController.java
  server/src/main/java/com/vip/interviewpartner/dto/QuestionLookupResponse.java
  server/src/main/java/com/vip/interviewpartner/repository/InterviewRepository.java
  server/src/main/java/com/vip/interviewpartner/repository/QuestionRepository.java
  server/src/main/java/com/vip/interviewpartner/service/QuestionFinderService.java
Labels: 🔥 BE, ✨ Feature

#90 feat: 자신의 모의면접 방 참가 이력을 조회하는 API 작성
  server/src/main/java/com/vip/interviewpartner/controller/MemberController.java
  server/src/main/java/com/vip/interviewpartner/dto/FeedbackCountDTO.java
  server/src/main/java/com/vip/interviewpartner/dto/ParticipationResponse.java
  server/src/main/java/com/vip/interviewpartner/repository/FeedbackRepository.java
  server/src/main/java/com/vip/interviewpartner/repository/RoomParticipantRepository.java
  server/src/main/java/com/vip/interviewpartner/service/ParticipantLookupService.java
  server/src/main/java/com/vip/interviewpartner/service/RoomParticipantService.java
Labels: 🔥 BE, ✨ Feature

#89 feat: openVidu 사용하여 모의면접 페이지에서 화상통화 및 채팅 기능 구현
  client/package-lock.json
  client/package.json
  client/src/assets/icons/rate_review_Icon.png
  client/src/components/UserVideoComponent.js
  client/src/index.js
  client/src/pages/mockupcommunity/ResumeSelectModal.jsx
  client/src/pages/mockuproom/chat.jsx
  client/src/pages/mockuproom/chatstyle.js
  client/src/pages/mockuproom/mockuproom.jsx
  client/src/pages/mockuproom/mockuproomstyle.js
  client/src/serviceWorkerRegistration.js
  client/src/services/openviduService.js
Labels: 🌈 FE, ✨ Feature
