Repository interview-partner/interview-partner, pull requests merged in 2024-06, with the labels that each got.

#91 feat: 답변 저장 API 작성
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/controller/InterviewController.java
  server/src/main/java/com/vip/interviewpartner/controller/QuestionController.java
  server/src/main/java/com/vip/interviewpartner/domain/UserAnswer.java
  server/src/main/java/com/vip/interviewpartner/dto/AnswerSaveRequest.java
  server/src/main/java/com/vip/interviewpartner/dto/InterviewCreateRequest.java
  server/src/main/java/com/vip/interviewpartner/repository/InterviewRepository.java
  server/src/main/java/com/vip/interviewpartner/repository/QuestionRepository.java
  server/src/main/java/com/vip/interviewpartner/service/AnswerSaveService.java
  server/src/main/java/com/vip/interviewpartner/service/InterviewCreateService.java
  server/src/main/java/com/vip/interviewpartner/service/InterviewService.java
  server/src/main/java/com/vip/interviewpartner/service/QuestionCreateService.java
  server/src/main/java/com/vip/interviewpartner/service/QuestionLookupService.java
Labels: 🔥 BE, ✨ Feature

#94 refactor: 모의면접 페이지 리팩토링
  client/package-lock.json
  client/package.json
  client/src/assets/icons/chevron_right_Icon.png
  client/src/assets/icons/diversity_3_Icon.png
  client/src/pages/mockupcommunity/CreateRoomModal.jsx
  client/src/pages/mockupcommunity/CreateRoomModalStyles.jsx
  client/src/pages/mockupcommunity/MockupCommunityStyles.jsx
  client/src/pages/mockupcommunity/Pagination.jsx
  client/src/pages/mockupcommunity/ResumeSelectModalStyles.jsx
  client/src/pages/mockupcommunity/mockupcommunity.jsx
  client/src/pages/mockuproom/chatstyle.js
  client/src/pages/mockuproom/mockuproom.jsx
  client/src/utils/dateUtils.jsx
  client/src/utils/tagUtils.jsx
  client/src/utils/validators.jsx
Labels: 🌈 FE, 🔨 Refactor

#98 feat: 모의 면접 중 채팅창에서 면접 참여자들의 이력서를 확인할 수 있는 기능 구현
  client/src/pages/mockuproom/ResumeViewer.jsx
  client/src/pages/mockuproom/chat.jsx
  client/src/pages/mockuproom/chatstyle.js
  client/src/pages/mockuproom/mockuproom.jsx
  client/src/pages/mockuproom/mockuproomstyle.js
Labels: 🌈 FE, ✨ Feature

#96 feat: 모의 면접 방 참여 이력 상세 조회 API 작성
  server/src/main/java/com/vip/interviewpartner/controller/ParticipantController.java
  server/src/main/java/com/vip/interviewpartner/dto/ParticipantDetailsResponse.java
  server/src/main/java/com/vip/interviewpartner/repository/RoomParticipantRepository.java
  server/src/main/java/com/vip/interviewpartner/service/RoomParticipantService.java
Labels: 🔥 BE, ✨ Feature

#100 feat: 특정 참여 이력에 대한 피드백 조회 API 작성
  db/init.sql
  server/src/main/java/com/vip/interviewpartner/InterviewPartnerApplication.java
  server/src/main/java/com/vip/interviewpartner/common/util/DateTimeUtil.java
  server/src/main/java/com/vip/interviewpartner/controller/MemberController.java
  server/src/main/java/com/vip/interviewpartner/controller/ParticipantController.java
  server/src/main/java/com/vip/interviewpartner/dto/FeedbackResponse.java
  server/src/main/java/com/vip/interviewpartner/dto/MemberInfoResponse.java
  server/src/main/java/com/vip/interviewpartner/dto/ParticipantDetailsResponse.java
  server/src/main/java/com/vip/interviewpartner/dto/ParticipationResponse.java
  server/src/main/java/com/vip/interviewpartner/dto/RoomResponseDTO.java
  server/src/main/java/com/vip/interviewpartner/repository/FeedbackRepository.java
  server/src/main/java/com/vip/interviewpartner/service/FeedbackCreateService.java
  server/src/main/java/com/vip/interviewpartner/service/FeedbackService.java
  server/src/main/java/com/vip/interviewpartner/service/RoomParticipantService.java
Labels: 🔥 BE, ✨ Feature

#101 feat: 모의 면접 중 채팅창에서 면접 참여자들끼리 피드백을 남길 수 있는 기능 구현
  client/package-lock.json
  client/package.json
  client/src/pages/mockupcommunity/Pagination.jsx
  client/src/pages/mockuproom/FeedbackForm.jsx
  client/src/pages/mockuproom/chat.jsx
  client/src/pages/mockuproom/chatstyle.jsx
  client/src/pages/mockuproom/mockuproom.jsx
  client/src/pages/mockuproom/mockuproomstyle.jsx
  client/src/services/feedbackService.js
  client/src/services/openviduService.js
Labels: 🌈 FE, ✨ Feature

#102 feat: AI 인터뷰 방 생성 api 적용
  client/public/index.html
  client/src/ModalPortal.js
  client/src/assets/icons/activeCheckCircle.png
  client/src/assets/icons/plusCircle.png
  client/src/assets/icons/refreshIcon.png
  client/src/assets/icons/unactiveCheckCircle.png
  client/src/assets/icons/uploadIcon.png
  client/src/assets/images/checkMethodType.png
  client/src/components/button/UploadResumeButton.jsx
  client/src/components/button/bigsquareButton.jsx
  client/src/components/button/counterButton.jsx
  client/src/components/button/resumeListButton.jsx
  client/src/components/button/resumeUploadButton.jsx
  client/src/components/button/showPaper.jsx
  client/src/features/banner/interviewInfo.jsx
  client/src/features/input/InputInterviewInfo.jsx
  client/src/features/input/InputInterviewSetting.jsx
  client/src/features/input/InputPersonalInfo.jsx
  client/src/features/input/InputResumeSelect.jsx
  client/src/features/input/Inputready.jsx
  client/src/features/modal/ResumeUploadModal.jsx
  client/src/features/show-list/resumeList.jsx
  client/src/pages/aiinterview/aiinterview.jsx
  client/src/pages/promptroom/promptroom.jsx
  client/src/services/checkResumeService.js
  client/src/services/interviewService.js
  client/src/services/resumeUploadService.js
Labels: 🌈 FE, ✨ Feature

#104 feat: 프롬프트 방에서 필요한 인터뷰 정보 조회 API 구현
  server/src/main/java/com/vip/interviewpartner/controller/InterviewController.java
  server/src/main/java/com/vip/interviewpartner/dto/InterviewLookupResponse.java
  server/src/main/java/com/vip/interviewpartner/repository/ResumeRepository.java
  server/src/main/java/com/vip/interviewpartner/service/InterviewService.java
Labels: 🔥 BE, ✨ Feature

#111 FIX: 이력서 업로드 버그 수정
  client/src/components/button/smallsquareButton.jsx
  client/src/features/banner/interviewInfo.jsx
  client/src/features/input/InputInterviewSetting.jsx
  client/src/features/input/InputResumeSelect.jsx
  client/src/features/modal/ResumeUploadModal.jsx
  client/src/features/show-list/resumeList.jsx
Labels: 🐞 BugFix, 🌈 FE

#113 feat: 마이페이지에서 필요한 사용자 인터뷰 정보 조회 API 구현
  server/src/main/java/com/vip/interviewpartner/controller/MemberController.java
  server/src/main/java/com/vip/interviewpartner/dto/MemberInterviewLookupResponse.java
  server/src/main/java/com/vip/interviewpartner/repository/InterviewRepository.java
  server/src/main/java/com/vip/interviewpartner/service/InterviewService.java
Labels: 🔥 BE, ✨ Feature

#115 feat: 꼬리 질문 생성 API 구현
  server/src/main/java/com/vip/interviewpartner/controller/QuestionController.java
  server/src/main/java/com/vip/interviewpartner/domain/Question.java
  server/src/main/java/com/vip/interviewpartner/dto/TailQuestionResponse.java
  server/src/main/java/com/vip/interviewpartner/repository/UserAnswerRepository.java
  server/src/main/java/com/vip/interviewpartner/service/TailQuestionCreateService.java
Labels: 🔥 BE, ✨ Feature

#117 fix: progressbar 버그 해결
  client/src/features/input/InputInterviewInfo.jsx
  client/src/features/show-progress/SelectInterviewInfo.jsx
  client/src/pages/aiinterview/aiinterview.jsx
Labels: 🐞 BugFix, 🌈 FE

#119 refactor: 가독성을 위한 꼬리 질문 요청 메서드 위치 변경
  server/src/main/java/com/vip/interviewpartner/service/QuestionCreateService.java
  server/src/main/java/com/vip/interviewpartner/service/TailQuestionCreateService.java
Labels: 🔨 Refactor, 🔥 BE

#121 feat: mypage 배너 구현
  client/src/assets/icons/IDcard.png
  client/src/assets/icons/account.png
  client/src/assets/icons/mail.png
  client/src/assets/icons/phone.png
  client/src/components/button/AccountCircleButton.jsx
  client/src/components/layout/navBar.js
  client/src/features/banner/accountInfo.jsx
  client/src/pages/mypage/mypage.css
  client/src/pages/mypage/mypage.jsx
  client/src/pages/promptroom/promptroom.css
Labels: 🌈 FE, ✨ Feature

#123 feat: 꼬리질문 생성 기능 구현
  client/src/assets/icons/arrow_blue.png
  client/src/assets/icons/question_fill.png
  client/src/assets/icons/question_line.png
  client/src/components/button/RoundButton.jsx
  client/src/components/shape/FollowUpQuestion.jsx
  client/src/components/shape/QuestionNumber.jsx
  client/src/components/textbox/aidialogBox.jsx
  client/src/features/chat/interviewChat.jsx
  client/src/services/followUpQuestionService.js
  client/src/services/saveAnswerService.js
Labels: 🌈 FE, ✨ Feature

#126 refactor: 텍스트 수 제한으로 프롬프트 변경
  server/src/main/java/com/vip/interviewpartner/service/QuestionCreateService.java
Labels: 🔨 Refactor, 🔥 BE

#128 feat: 마이페이지 개발
  client/src/assets/icons/chevron_left_Icon_gray.png
  client/src/assets/icons/chevron_right_Icon_gray.png
  client/src/assets/icons/chevron_right_Icon_skyblue.png
  client/src/assets/icons/event_available_Icon_white.png
  client/src/assets/icons/psychology_Icon_skyblue.png
  client/src/assets/icons/video_camera_front_Icon_skyblue.png
  client/src/features/banner/accountInfo.jsx
  client/src/pages/mypage/InterviewManageSection.jsx
  client/src/pages/mypage/Modal.jsx
  client/src/pages/mypage/ResumeManageSection.jsx
  client/src/pages/mypage/mypage.jsx
  client/src/services/getAIInterviewsService.js
  client/src/services/memberInfoService.js
  client/src/services/roomService.js
  client/src/utils/dateUtils.jsx
Labels: 🌈 FE, ✨ Feature

#135 feat: favicon.ico 변경 및 웹 타이틀 변경
  client/public/favicon.ico
  client/public/index.html
Labels: 🌈 FE, ✨ Feature

#139 refactor: 꼬리질문 프롬프트 변경
  server/src/main/java/com/vip/interviewpartner/service/QuestionCreateService.java
Labels: 🔨 Refactor, 🔥 BE

#140 release: version 0.0.2
  server/src/main/java/com/vip/interviewpartner/service/QuestionCreateService.java
Labels: 🌏 Deploy

#142 fix: 꼬리질문 및 질문 프롬프트 변경 (#141)
  server/src/main/java/com/vip/interviewpartner/common/util/JsonStringEscapeConverter.java
  server/src/main/java/com/vip/interviewpartner/service/QuestionCreateService.java
Labels: 🐞 BugFix, 🔥 BE

#146 refactor: Google STT 설정 변경
  server/src/main/java/com/vip/interviewpartner/common/exception/ErrorCode.java
  server/src/main/java/com/vip/interviewpartner/controller/QuestionController.java
  server/src/main/java/com/vip/interviewpartner/service/GoogleSttService.java
  server/src/main/java/com/vip/interviewpartner/service/S3UploadService.java
Labels: 🔨 Refactor, 🔥 BE

#154 refactor: 로그인 폼 리팩토링 및 모의면접, 마이페이지 기능 관련 주석 추가
  client/src/config.js
  client/src/features/login/accountBox/loginForm.jsx
  client/src/pages/mockupcommunity/CreateRoomModal.jsx
  client/src/pages/mockupcommunity/CreateRoomModalStyles.jsx
  client/src/pages/mockupcommunity/ResumeSelectModal.jsx
  client/src/pages/mockupcommunity/mockupcommunity.jsx
  client/src/pages/mockuproom/chat.jsx
  client/src/pages/mockuproom/mockuproom.jsx
  client/src/pages/mockuproom/mockuproomstyle.jsx
  client/src/pages/mypage/ResumeManageSection.jsx
  client/src/pages/mypage/mypage.jsx
  client/src/services/loginService.js
Labels: 🌈 FE, 🔨 Refactor

#155 refactor: aiinterview 디자인 수정 및 로직 변경
  client/src/assets/icons/send_blue.png
  client/src/assets/icons/voice_blue.png
  client/src/assets/icons/voice_grey.png
  client/src/components/button/UploadResumeButton.jsx
  client/src/components/button/VoiceroomButton.jsx
  client/src/components/button/counterButton.jsx
  client/src/features/banner/interviewInfo.jsx
  client/src/features/chat/TextInput.jsx
  client/src/features/chat/VoiceInput.jsx
  client/src/features/chat/interviewChat.jsx
  client/src/features/input/InputInterviewInfo.jsx
  client/src/features/input/InputInterviewSetting.jsx
  client/src/features/input/Inputready.jsx
  client/src/features/modal/InterviewLoadingModal.jsx
  client/src/features/modal/VoiceCheckModal.jsx
  client/src/pages/main/main.jsx
  client/src/pages/promptroom/promptroom.jsx
  client/src/pages/voiceroom/voiceroom.css
  node_modules/.package-lock.json
  node_modules/@ffmpeg/ffmpeg/dist/esm/classes.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/classes.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/const.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/const.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/empty.d.mts
  node_modules/@ffmpeg/ffmpeg/dist/esm/empty.mjs
  node_modules/@ffmpeg/ffmpeg/dist/esm/errors.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/errors.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/index.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/index.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/types.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/types.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/utils.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/utils.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/worker.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/worker.js
  node_modules/@ffmpeg/ffmpeg/dist/umd/814.ffmpeg.js
  node_modules/@ffmpeg/ffmpeg/dist/umd/814.ffmpeg.js.map
  node_modules/@ffmpeg/ffmpeg/dist/umd/ffmpeg.js
  node_modules/@ffmpeg/ffmpeg/dist/umd/ffmpeg.js.map
  node_modules/@ffmpeg/ffmpeg/package.json
  node_modules/@ffmpeg/types/package.json
  node_modules/@ffmpeg/types/types/index.d.ts
  package-lock.json
  package.json
Labels: 🌈 FE, 🔨 Refactor, 🖌️ Design

#156 release: version 1.0.0
  LICENSE
  NOTICE
  README.md
  client/src/assets/icons/send_blue.png
  client/src/assets/icons/voice_blue.png
  client/src/assets/icons/voice_grey.png
  client/src/components/button/UploadResumeButton.jsx
  client/src/components/button/VoiceroomButton.jsx
  client/src/components/button/counterButton.jsx
  client/src/config.js
  client/src/features/banner/interviewInfo.jsx
  client/src/features/chat/TextInput.jsx
  client/src/features/chat/VoiceInput.jsx
  client/src/features/chat/interviewChat.jsx
  client/src/features/input/InputInterviewInfo.jsx
  client/src/features/input/InputInterviewSetting.jsx
  client/src/features/input/Inputready.jsx
  client/src/features/login/accountBox/loginForm.jsx
  client/src/features/modal/InterviewLoadingModal.jsx
  client/src/features/modal/VoiceCheckModal.jsx
  client/src/pages/main/main.jsx
  client/src/pages/mockupcommunity/CreateRoomModal.jsx
  client/src/pages/mockupcommunity/CreateRoomModalStyles.jsx
  client/src/pages/mockupcommunity/ResumeSelectModal.jsx
  client/src/pages/mockupcommunity/mockupcommunity.jsx
  client/src/pages/mockuproom/chat.jsx
  client/src/pages/mockuproom/mockuproom.jsx
  client/src/pages/mockuproom/mockuproomstyle.jsx
  client/src/pages/mypage/ResumeManageSection.jsx
  client/src/pages/mypage/mypage.jsx
  client/src/pages/promptroom/promptroom.jsx
  client/src/pages/voiceroom/voiceroom.css
  client/src/services/loginService.js
  node_modules/.package-lock.json
  node_modules/@ffmpeg/ffmpeg/dist/esm/classes.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/classes.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/const.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/const.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/empty.d.mts
  node_modules/@ffmpeg/ffmpeg/dist/esm/empty.mjs
  node_modules/@ffmpeg/ffmpeg/dist/esm/errors.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/errors.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/index.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/index.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/types.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/types.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/utils.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/utils.js
  node_modules/@ffmpeg/ffmpeg/dist/esm/worker.d.ts
  node_modules/@ffmpeg/ffmpeg/dist/esm/worker.js
  node_modules/@ffmpeg/ffmpeg/dist/umd/814.ffmpeg.js
  node_modules/@ffmpeg/ffmpeg/dist/umd/814.ffmpeg.js.map
  node_modules/@ffmpeg/ffmpeg/dist/umd/ffmpeg.js
  node_modules/@ffmpeg/ffmpeg/dist/umd/ffmpeg.js.map
  node_modules/@ffmpeg/ffmpeg/package.json
  node_modules/@ffmpeg/types/package.json
  node_modules/@ffmpeg/types/types/index.d.ts
  package-lock.json
  package.json
Labels: 🌏 Deploy
